services:
  postgres:
    image: postgres
    container_name: postgres-balance-system
    environment:
      POSTGRES_DB: "balancesystem"
      POSTGRES_USER: "balancesystem"
      POSTGRES_PASSWORD: "balancesystem"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: unless-stopped

  redis:
    image: redis
    container_name: redis-balance-system
    ports:
      - "6379:6379"
  web:
    build: .
    command: >
      sh -c "poetry run python manage.py migrate &&
              poetry run python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
  celery:
    build: .
    command: poetry run celery -A config worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis

volumes:
  postgres_data:
