# Generated by Django 5.1.1 on 2024-10-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balance", "0005_transaction_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="balance",
            name="amount",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
