# Generated by Django 5.1.1 on 2024-10-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balance", "0002_alter_transaction_options_transaction_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="action",
            field=models.CharField(
                choices=[("deposit", "Deposit"), ("withdraw", "Withdraw")],
                default="deposit",
                max_length=10,
            ),
        ),
    ]
