# Generated by Django 5.1.1 on 2024-10-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balance", "0003_transaction_action"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AddField(
            model_name="balance",
            name="currency",
            field=models.CharField(
                choices=[("₽", "₽"), ("$", "$")], default="₽", max_length=3
            ),
        ),
    ]
