# Generated by Django 5.1.1 on 2024-10-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balance", "0004_alter_transaction_options_balance_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
